name: Publish to Maven Central

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Publish with Gradle
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: ./gradlew clean publish

      - name: Notify Sonatype Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          curl -u "${OSSRH_USERNAME}:${OSSRH_PASSWORD}" \
          -X POST \
          "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.imranrasulzade"